global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api-unidades-organizacionais"
    static_configs:
      - targets: ["app:3000"]
    metrics_path: "/metrics"

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8888"]

  - job_name: "otel-collector-metrics"
    static_configs:
      - targets: ["otel-collector:8889"]
